"""add balance_before and balance_after to balance_transactions

Revision ID: 6401a9f62787
Revises: 046f48aa2e35
Create Date: 2025-09-19 23:32:53.991017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6401a9f62787"
down_revision: Union[str, None] = "046f48aa2e35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balance_transactions",
        sa.Column(
            "balance_before", sa.Numeric(precision=18, scale=6), nullable=False
        ),
    )
    op.add_column(
        "balance_transactions",
        sa.Column(
            "balance_after", sa.Numeric(precision=18, scale=6), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("balance_transactions", "balance_after")
    op.drop_column("balance_transactions", "balance_before")
    # ### end Alembic commands ###
