"""add merchant_id and trader_id fields to MerchantTraderLink

Revision ID: 65794e775c5c
Revises: 90ab958c989d
Create Date: 2025-09-21 10:44:32.301596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65794e775c5c"
down_revision: Union[str, None] = "90ab958c989d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
